### ISSUE TITLE
Add log system.

### ISSUE THREAD

**Issue by lychees** [yukiexe/eoscrazytown#1]

**Comment by yukiexe** [comment]
card dragon = seed.hash[ 0 ] % 52 ;
    card tiger = seed.hash[ 1 ] % 52 ;
    const rec_reveal _reveal{
        .dragon = dragon,
        .tiger = tiger,
        .server_hash = _global.get().hash,
        .client_seed = seed,
    };
    
    action( // give result to client
            permission_level{_self, N(active)},
            _self, N(receipt), _reveal
    ).send();
